### ISSUE TITLE
Decide the Coding Language

### ISSUE THREAD

**Issue by shubham9411** [shubham9411/ideas#1]
- [x] PHP
- [ ] CSS
- [ ] C++
- [x] Python
- [x] JS
- [ ] Angular
- [ ] React
- [ ] Android
- [ ] Java
- [ ] Sass

**Comment by shubham9411** [comment]
We can create an application that uses AJAX for all the DB interactions. More like an SPA by using angular or jQuery. 
I have added JS also.
Let us discuss about it. Just wanted to try out making a good UX. Let me know your point of view in this! cheers!

**Comment by Yathartha22** [comment]
Probably this could be a good idea. If only DB interactions are to be done we can use Python instead, I guess it will be more simpler. Ajax could be used in front-end rather.

**Comment by shubham9411** [comment]
We can use Django Framework for backend along with the Angular or React for AJAXifying the Application. I am adding a new list for the database lang we can use : 
- [ ] MySQL
- [ ] Orace
- [ ] MongoDB
- [ ] SQLite3
I have seen so far is that the Django developers tend to use the SQLite. And it may be useful if we switch to a new language for this project, SQLite maybe. 
Counting on you!

**Comment by Yathartha22** [comment]
SQLite3 will be a good choice. We are quite familiar with MySQL and I found SQLite3 pretty much familiar with it rather it being lightweight.
Also for reference checkout [link](http://stackoverflow.com/questions/9540154/which-database-engine-to-choose-for-django-app).

**Comment by Yathartha22** [comment]
I guess we have sorted the required number of languages for our application.
Django for the backend along with Angular .
SQLite3 as a database engine.

We will be using android in future ;) .

**Comment by shubham9411** [comment]
Agree with you! but I find that the link from StackOverflow just talks about the MySQL and PostgreSQL comparison. There is no reference for using the SQLite3.

**Comment by Yathartha22** [comment]
The link was just a reference what database engine to chose for using Django. Nothing linked to SQLite3.

**Comment by shubham9411** [comment]
So What's the plan then? :)

**Comment by Yathartha22** [comment]
The first thing
 what should the application be, what should it focus on.

**Comment by shubham9411** [comment]
What about the idea of creating a RSS Feed Listener with Task/TODO manager.

**Comment by Yathartha22** [comment]
As of now we can start working on it.
