### ISSUE TITLE
React Front End for a WP back end

### ISSUE THREAD

**Issue by shubham9411** [shubham9411/ideas#4]
Create a theme that uses React for the Front end and WordPress in the Backend. 👍

**Comment by Yathartha22** [comment]
I'm in.

**Comment by Yathartha22** [comment]
I'm not really familiar with `React`. I would appreciate if you could get me through the the basics of it.

**Comment by shubham9411** [comment]
@Yathartha22 actually the thing is I want to learn the `React` thingy. Bro! We are on the same page. :nerd_face:

**Comment by Yathartha22** [comment]
:D okay, then we should start learning it soon. What could be the best resource to start with?

**Comment by shubham9411** [comment]
React Official Documentation at https://facebook.github.io/react/ you can have it locally on your system also 😄
